# Generated by Django 2.2.7 on 2019-12-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20191127_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='house_rule',
        ),
        migrations.AddField(
            model_name='room',
            name='house_rules',
            field=models.ManyToManyField(blank=True, to='rooms.HouseRule'),
        ),
    ]
