# Generated by Django 2.2.7 on 2019-12-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20191216_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
